<?php
/**
 * GetDirectoryStats200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lockally\SDK\Model;

use \ArrayAccess;
use \Lockally\SDK\ObjectSerializer;

/**
 * GetDirectoryStats200Response Class Doc Comment
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetDirectoryStats200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'getDirectoryStats_200_response';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'total_contacts' => 'int',
        'internal_users' => 'int',
        'external_contacts' => 'int',
        'synced_contacts' => 'int',
        'shared_lists' => 'int',
        'directory_groups' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'total_contacts' => null,
        'internal_users' => null,
        'external_contacts' => null,
        'synced_contacts' => null,
        'shared_lists' => null,
        'directory_groups' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'total_contacts' => false,
        'internal_users' => false,
        'external_contacts' => false,
        'synced_contacts' => false,
        'shared_lists' => false,
        'directory_groups' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_contacts' => 'total_contacts',
        'internal_users' => 'internal_users',
        'external_contacts' => 'external_contacts',
        'synced_contacts' => 'synced_contacts',
        'shared_lists' => 'shared_lists',
        'directory_groups' => 'directory_groups'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_contacts' => 'setTotalContacts',
        'internal_users' => 'setInternalUsers',
        'external_contacts' => 'setExternalContacts',
        'synced_contacts' => 'setSyncedContacts',
        'shared_lists' => 'setSharedLists',
        'directory_groups' => 'setDirectoryGroups'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_contacts' => 'getTotalContacts',
        'internal_users' => 'getInternalUsers',
        'external_contacts' => 'getExternalContacts',
        'synced_contacts' => 'getSyncedContacts',
        'shared_lists' => 'getSharedLists',
        'directory_groups' => 'getDirectoryGroups'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('total_contacts', $data ?? [], null);
        $this->setIfExists('internal_users', $data ?? [], null);
        $this->setIfExists('external_contacts', $data ?? [], null);
        $this->setIfExists('synced_contacts', $data ?? [], null);
        $this->setIfExists('shared_lists', $data ?? [], null);
        $this->setIfExists('directory_groups', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_contacts
     *
     * @return int|null
     */
    public function getTotalContacts()
    {
        return $this->container['total_contacts'];
    }

    /**
     * Sets total_contacts
     *
     * @param int|null $total_contacts total_contacts
     *
     * @return self
     */
    public function setTotalContacts($total_contacts)
    {
        if (is_null($total_contacts)) {
            throw new \InvalidArgumentException('non-nullable total_contacts cannot be null');
        }
        $this->container['total_contacts'] = $total_contacts;

        return $this;
    }

    /**
     * Gets internal_users
     *
     * @return int|null
     */
    public function getInternalUsers()
    {
        return $this->container['internal_users'];
    }

    /**
     * Sets internal_users
     *
     * @param int|null $internal_users internal_users
     *
     * @return self
     */
    public function setInternalUsers($internal_users)
    {
        if (is_null($internal_users)) {
            throw new \InvalidArgumentException('non-nullable internal_users cannot be null');
        }
        $this->container['internal_users'] = $internal_users;

        return $this;
    }

    /**
     * Gets external_contacts
     *
     * @return int|null
     */
    public function getExternalContacts()
    {
        return $this->container['external_contacts'];
    }

    /**
     * Sets external_contacts
     *
     * @param int|null $external_contacts external_contacts
     *
     * @return self
     */
    public function setExternalContacts($external_contacts)
    {
        if (is_null($external_contacts)) {
            throw new \InvalidArgumentException('non-nullable external_contacts cannot be null');
        }
        $this->container['external_contacts'] = $external_contacts;

        return $this;
    }

    /**
     * Gets synced_contacts
     *
     * @return int|null
     */
    public function getSyncedContacts()
    {
        return $this->container['synced_contacts'];
    }

    /**
     * Sets synced_contacts
     *
     * @param int|null $synced_contacts synced_contacts
     *
     * @return self
     */
    public function setSyncedContacts($synced_contacts)
    {
        if (is_null($synced_contacts)) {
            throw new \InvalidArgumentException('non-nullable synced_contacts cannot be null');
        }
        $this->container['synced_contacts'] = $synced_contacts;

        return $this;
    }

    /**
     * Gets shared_lists
     *
     * @return int|null
     */
    public function getSharedLists()
    {
        return $this->container['shared_lists'];
    }

    /**
     * Sets shared_lists
     *
     * @param int|null $shared_lists shared_lists
     *
     * @return self
     */
    public function setSharedLists($shared_lists)
    {
        if (is_null($shared_lists)) {
            throw new \InvalidArgumentException('non-nullable shared_lists cannot be null');
        }
        $this->container['shared_lists'] = $shared_lists;

        return $this;
    }

    /**
     * Gets directory_groups
     *
     * @return int|null
     */
    public function getDirectoryGroups()
    {
        return $this->container['directory_groups'];
    }

    /**
     * Sets directory_groups
     *
     * @param int|null $directory_groups directory_groups
     *
     * @return self
     */
    public function setDirectoryGroups($directory_groups)
    {
        if (is_null($directory_groups)) {
            throw new \InvalidArgumentException('non-nullable directory_groups cannot be null');
        }
        $this->container['directory_groups'] = $directory_groups;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


