<?php
/**
 * GetUserInsights200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lockally\SDK\Model;

use \ArrayAccess;
use \Lockally\SDK\ObjectSerializer;

/**
 * GetUserInsights200Response Class Doc Comment
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetUserInsights200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'getUserInsights_200_response';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'recently_added' => '\Lockally\SDK\Model\UserEvent[]',
        'recently_suspended' => '\Lockally\SDK\Model\UserEvent[]',
        'inactive_30d' => '\Lockally\SDK\Model\UserEvent[]',
        'seats_used' => 'int',
        'seats_alloc' => 'int',
        'seats_capped' => 'bool',
        'generated_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'recently_added' => null,
        'recently_suspended' => null,
        'inactive_30d' => null,
        'seats_used' => null,
        'seats_alloc' => null,
        'seats_capped' => null,
        'generated_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'recently_added' => false,
        'recently_suspended' => false,
        'inactive_30d' => false,
        'seats_used' => false,
        'seats_alloc' => false,
        'seats_capped' => false,
        'generated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'recently_added' => 'recently_added',
        'recently_suspended' => 'recently_suspended',
        'inactive_30d' => 'inactive_30d',
        'seats_used' => 'seats_used',
        'seats_alloc' => 'seats_alloc',
        'seats_capped' => 'seats_capped',
        'generated_at' => 'generated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'recently_added' => 'setRecentlyAdded',
        'recently_suspended' => 'setRecentlySuspended',
        'inactive_30d' => 'setInactive30d',
        'seats_used' => 'setSeatsUsed',
        'seats_alloc' => 'setSeatsAlloc',
        'seats_capped' => 'setSeatsCapped',
        'generated_at' => 'setGeneratedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'recently_added' => 'getRecentlyAdded',
        'recently_suspended' => 'getRecentlySuspended',
        'inactive_30d' => 'getInactive30d',
        'seats_used' => 'getSeatsUsed',
        'seats_alloc' => 'getSeatsAlloc',
        'seats_capped' => 'getSeatsCapped',
        'generated_at' => 'getGeneratedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('recently_added', $data ?? [], null);
        $this->setIfExists('recently_suspended', $data ?? [], null);
        $this->setIfExists('inactive_30d', $data ?? [], null);
        $this->setIfExists('seats_used', $data ?? [], null);
        $this->setIfExists('seats_alloc', $data ?? [], null);
        $this->setIfExists('seats_capped', $data ?? [], null);
        $this->setIfExists('generated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets recently_added
     *
     * @return \Lockally\SDK\Model\UserEvent[]|null
     */
    public function getRecentlyAdded()
    {
        return $this->container['recently_added'];
    }

    /**
     * Sets recently_added
     *
     * @param \Lockally\SDK\Model\UserEvent[]|null $recently_added recently_added
     *
     * @return self
     */
    public function setRecentlyAdded($recently_added)
    {
        if (is_null($recently_added)) {
            throw new \InvalidArgumentException('non-nullable recently_added cannot be null');
        }
        $this->container['recently_added'] = $recently_added;

        return $this;
    }

    /**
     * Gets recently_suspended
     *
     * @return \Lockally\SDK\Model\UserEvent[]|null
     */
    public function getRecentlySuspended()
    {
        return $this->container['recently_suspended'];
    }

    /**
     * Sets recently_suspended
     *
     * @param \Lockally\SDK\Model\UserEvent[]|null $recently_suspended recently_suspended
     *
     * @return self
     */
    public function setRecentlySuspended($recently_suspended)
    {
        if (is_null($recently_suspended)) {
            throw new \InvalidArgumentException('non-nullable recently_suspended cannot be null');
        }
        $this->container['recently_suspended'] = $recently_suspended;

        return $this;
    }

    /**
     * Gets inactive_30d
     *
     * @return \Lockally\SDK\Model\UserEvent[]|null
     */
    public function getInactive30d()
    {
        return $this->container['inactive_30d'];
    }

    /**
     * Sets inactive_30d
     *
     * @param \Lockally\SDK\Model\UserEvent[]|null $inactive_30d inactive_30d
     *
     * @return self
     */
    public function setInactive30d($inactive_30d)
    {
        if (is_null($inactive_30d)) {
            throw new \InvalidArgumentException('non-nullable inactive_30d cannot be null');
        }
        $this->container['inactive_30d'] = $inactive_30d;

        return $this;
    }

    /**
     * Gets seats_used
     *
     * @return int|null
     */
    public function getSeatsUsed()
    {
        return $this->container['seats_used'];
    }

    /**
     * Sets seats_used
     *
     * @param int|null $seats_used seats_used
     *
     * @return self
     */
    public function setSeatsUsed($seats_used)
    {
        if (is_null($seats_used)) {
            throw new \InvalidArgumentException('non-nullable seats_used cannot be null');
        }
        $this->container['seats_used'] = $seats_used;

        return $this;
    }

    /**
     * Gets seats_alloc
     *
     * @return int|null
     */
    public function getSeatsAlloc()
    {
        return $this->container['seats_alloc'];
    }

    /**
     * Sets seats_alloc
     *
     * @param int|null $seats_alloc seats_alloc
     *
     * @return self
     */
    public function setSeatsAlloc($seats_alloc)
    {
        if (is_null($seats_alloc)) {
            throw new \InvalidArgumentException('non-nullable seats_alloc cannot be null');
        }
        $this->container['seats_alloc'] = $seats_alloc;

        return $this;
    }

    /**
     * Gets seats_capped
     *
     * @return bool|null
     */
    public function getSeatsCapped()
    {
        return $this->container['seats_capped'];
    }

    /**
     * Sets seats_capped
     *
     * @param bool|null $seats_capped True only on tiers with a hard seat cap (Free, Founder). On unlimited/per-seat tiers seats_alloc merely tracks the live mailbox count, so seats_used == seats_alloc is normal and must not be read as 'at capacity'.
     *
     * @return self
     */
    public function setSeatsCapped($seats_capped)
    {
        if (is_null($seats_capped)) {
            throw new \InvalidArgumentException('non-nullable seats_capped cannot be null');
        }
        $this->container['seats_capped'] = $seats_capped;

        return $this;
    }

    /**
     * Gets generated_at
     *
     * @return \DateTime|null
     */
    public function getGeneratedAt()
    {
        return $this->container['generated_at'];
    }

    /**
     * Sets generated_at
     *
     * @param \DateTime|null $generated_at generated_at
     *
     * @return self
     */
    public function setGeneratedAt($generated_at)
    {
        if (is_null($generated_at)) {
            throw new \InvalidArgumentException('non-nullable generated_at cannot be null');
        }
        $this->container['generated_at'] = $generated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


