<?php
/**
 * MigrationProgressMailboxesInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lockally\SDK\Model;

use \ArrayAccess;
use \Lockally\SDK\ObjectSerializer;

/**
 * MigrationProgressMailboxesInner Class Doc Comment
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MigrationProgressMailboxesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MigrationProgress_mailboxes_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'source_email' => 'string',
        'dest_email' => 'string',
        'status' => 'string',
        'source_message_count' => 'int',
        'synced_message_count' => 'int',
        'failed_message_count' => 'int',
        'percent_complete' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'source_email' => null,
        'dest_email' => null,
        'status' => null,
        'source_message_count' => null,
        'synced_message_count' => null,
        'failed_message_count' => null,
        'percent_complete' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'source_email' => false,
        'dest_email' => false,
        'status' => false,
        'source_message_count' => false,
        'synced_message_count' => false,
        'failed_message_count' => false,
        'percent_complete' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'source_email' => 'source_email',
        'dest_email' => 'dest_email',
        'status' => 'status',
        'source_message_count' => 'source_message_count',
        'synced_message_count' => 'synced_message_count',
        'failed_message_count' => 'failed_message_count',
        'percent_complete' => 'percent_complete'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'source_email' => 'setSourceEmail',
        'dest_email' => 'setDestEmail',
        'status' => 'setStatus',
        'source_message_count' => 'setSourceMessageCount',
        'synced_message_count' => 'setSyncedMessageCount',
        'failed_message_count' => 'setFailedMessageCount',
        'percent_complete' => 'setPercentComplete'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'source_email' => 'getSourceEmail',
        'dest_email' => 'getDestEmail',
        'status' => 'getStatus',
        'source_message_count' => 'getSourceMessageCount',
        'synced_message_count' => 'getSyncedMessageCount',
        'failed_message_count' => 'getFailedMessageCount',
        'percent_complete' => 'getPercentComplete'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('source_email', $data ?? [], null);
        $this->setIfExists('dest_email', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('source_message_count', $data ?? [], null);
        $this->setIfExists('synced_message_count', $data ?? [], null);
        $this->setIfExists('failed_message_count', $data ?? [], null);
        $this->setIfExists('percent_complete', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['source_email'] === null) {
            $invalidProperties[] = "'source_email' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['synced_message_count'] === null) {
            $invalidProperties[] = "'synced_message_count' can't be null";
        }
        if ($this->container['failed_message_count'] === null) {
            $invalidProperties[] = "'failed_message_count' can't be null";
        }
        if ($this->container['percent_complete'] === null) {
            $invalidProperties[] = "'percent_complete' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets source_email
     *
     * @return string
     */
    public function getSourceEmail()
    {
        return $this->container['source_email'];
    }

    /**
     * Sets source_email
     *
     * @param string $source_email source_email
     *
     * @return self
     */
    public function setSourceEmail($source_email)
    {
        if (is_null($source_email)) {
            throw new \InvalidArgumentException('non-nullable source_email cannot be null');
        }
        $this->container['source_email'] = $source_email;

        return $this;
    }

    /**
     * Gets dest_email
     *
     * @return string|null
     */
    public function getDestEmail()
    {
        return $this->container['dest_email'];
    }

    /**
     * Sets dest_email
     *
     * @param string|null $dest_email dest_email
     *
     * @return self
     */
    public function setDestEmail($dest_email)
    {
        if (is_null($dest_email)) {
            throw new \InvalidArgumentException('non-nullable dest_email cannot be null');
        }
        $this->container['dest_email'] = $dest_email;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets source_message_count
     *
     * @return int|null
     */
    public function getSourceMessageCount()
    {
        return $this->container['source_message_count'];
    }

    /**
     * Sets source_message_count
     *
     * @param int|null $source_message_count source_message_count
     *
     * @return self
     */
    public function setSourceMessageCount($source_message_count)
    {
        if (is_null($source_message_count)) {
            throw new \InvalidArgumentException('non-nullable source_message_count cannot be null');
        }
        $this->container['source_message_count'] = $source_message_count;

        return $this;
    }

    /**
     * Gets synced_message_count
     *
     * @return int
     */
    public function getSyncedMessageCount()
    {
        return $this->container['synced_message_count'];
    }

    /**
     * Sets synced_message_count
     *
     * @param int $synced_message_count synced_message_count
     *
     * @return self
     */
    public function setSyncedMessageCount($synced_message_count)
    {
        if (is_null($synced_message_count)) {
            throw new \InvalidArgumentException('non-nullable synced_message_count cannot be null');
        }
        $this->container['synced_message_count'] = $synced_message_count;

        return $this;
    }

    /**
     * Gets failed_message_count
     *
     * @return int
     */
    public function getFailedMessageCount()
    {
        return $this->container['failed_message_count'];
    }

    /**
     * Sets failed_message_count
     *
     * @param int $failed_message_count failed_message_count
     *
     * @return self
     */
    public function setFailedMessageCount($failed_message_count)
    {
        if (is_null($failed_message_count)) {
            throw new \InvalidArgumentException('non-nullable failed_message_count cannot be null');
        }
        $this->container['failed_message_count'] = $failed_message_count;

        return $this;
    }

    /**
     * Gets percent_complete
     *
     * @return float
     */
    public function getPercentComplete()
    {
        return $this->container['percent_complete'];
    }

    /**
     * Sets percent_complete
     *
     * @param float $percent_complete percent_complete
     *
     * @return self
     */
    public function setPercentComplete($percent_complete)
    {
        if (is_null($percent_complete)) {
            throw new \InvalidArgumentException('non-nullable percent_complete cannot be null');
        }
        $this->container['percent_complete'] = $percent_complete;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


