<?php
/**
 * UpdateGALSettingsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lockally\SDK\Model;

use \ArrayAccess;
use \Lockally\SDK\ObjectSerializer;

/**
 * UpdateGALSettingsRequest Class Doc Comment
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateGALSettingsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'updateGALSettings_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'gal_enabled' => 'bool',
        'hide_from_directory' => 'bool',
        'department_grouping' => 'bool',
        'search_visibility' => 'string',
        'include_external_contacts' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'gal_enabled' => null,
        'hide_from_directory' => null,
        'department_grouping' => null,
        'search_visibility' => null,
        'include_external_contacts' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'gal_enabled' => false,
        'hide_from_directory' => false,
        'department_grouping' => false,
        'search_visibility' => false,
        'include_external_contacts' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'gal_enabled' => 'gal_enabled',
        'hide_from_directory' => 'hide_from_directory',
        'department_grouping' => 'department_grouping',
        'search_visibility' => 'search_visibility',
        'include_external_contacts' => 'include_external_contacts'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'gal_enabled' => 'setGalEnabled',
        'hide_from_directory' => 'setHideFromDirectory',
        'department_grouping' => 'setDepartmentGrouping',
        'search_visibility' => 'setSearchVisibility',
        'include_external_contacts' => 'setIncludeExternalContacts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'gal_enabled' => 'getGalEnabled',
        'hide_from_directory' => 'getHideFromDirectory',
        'department_grouping' => 'getDepartmentGrouping',
        'search_visibility' => 'getSearchVisibility',
        'include_external_contacts' => 'getIncludeExternalContacts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SEARCH_VISIBILITY_ALL_USERS = 'all_users';
    public const SEARCH_VISIBILITY_SAME_DEPARTMENT = 'same_department';
    public const SEARCH_VISIBILITY_ADMINS_ONLY = 'admins_only';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSearchVisibilityAllowableValues()
    {
        return [
            self::SEARCH_VISIBILITY_ALL_USERS,
            self::SEARCH_VISIBILITY_SAME_DEPARTMENT,
            self::SEARCH_VISIBILITY_ADMINS_ONLY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('gal_enabled', $data ?? [], null);
        $this->setIfExists('hide_from_directory', $data ?? [], null);
        $this->setIfExists('department_grouping', $data ?? [], null);
        $this->setIfExists('search_visibility', $data ?? [], null);
        $this->setIfExists('include_external_contacts', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSearchVisibilityAllowableValues();
        if (!is_null($this->container['search_visibility']) && !in_array($this->container['search_visibility'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'search_visibility', must be one of '%s'",
                $this->container['search_visibility'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets gal_enabled
     *
     * @return bool|null
     */
    public function getGalEnabled()
    {
        return $this->container['gal_enabled'];
    }

    /**
     * Sets gal_enabled
     *
     * @param bool|null $gal_enabled gal_enabled
     *
     * @return self
     */
    public function setGalEnabled($gal_enabled)
    {
        if (is_null($gal_enabled)) {
            throw new \InvalidArgumentException('non-nullable gal_enabled cannot be null');
        }
        $this->container['gal_enabled'] = $gal_enabled;

        return $this;
    }

    /**
     * Gets hide_from_directory
     *
     * @return bool|null
     */
    public function getHideFromDirectory()
    {
        return $this->container['hide_from_directory'];
    }

    /**
     * Sets hide_from_directory
     *
     * @param bool|null $hide_from_directory hide_from_directory
     *
     * @return self
     */
    public function setHideFromDirectory($hide_from_directory)
    {
        if (is_null($hide_from_directory)) {
            throw new \InvalidArgumentException('non-nullable hide_from_directory cannot be null');
        }
        $this->container['hide_from_directory'] = $hide_from_directory;

        return $this;
    }

    /**
     * Gets department_grouping
     *
     * @return bool|null
     */
    public function getDepartmentGrouping()
    {
        return $this->container['department_grouping'];
    }

    /**
     * Sets department_grouping
     *
     * @param bool|null $department_grouping department_grouping
     *
     * @return self
     */
    public function setDepartmentGrouping($department_grouping)
    {
        if (is_null($department_grouping)) {
            throw new \InvalidArgumentException('non-nullable department_grouping cannot be null');
        }
        $this->container['department_grouping'] = $department_grouping;

        return $this;
    }

    /**
     * Gets search_visibility
     *
     * @return string|null
     */
    public function getSearchVisibility()
    {
        return $this->container['search_visibility'];
    }

    /**
     * Sets search_visibility
     *
     * @param string|null $search_visibility search_visibility
     *
     * @return self
     */
    public function setSearchVisibility($search_visibility)
    {
        if (is_null($search_visibility)) {
            throw new \InvalidArgumentException('non-nullable search_visibility cannot be null');
        }
        $allowedValues = $this->getSearchVisibilityAllowableValues();
        if (!in_array($search_visibility, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'search_visibility', must be one of '%s'",
                    $search_visibility,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['search_visibility'] = $search_visibility;

        return $this;
    }

    /**
     * Gets include_external_contacts
     *
     * @return bool|null
     */
    public function getIncludeExternalContacts()
    {
        return $this->container['include_external_contacts'];
    }

    /**
     * Sets include_external_contacts
     *
     * @param bool|null $include_external_contacts include_external_contacts
     *
     * @return self
     */
    public function setIncludeExternalContacts($include_external_contacts)
    {
        if (is_null($include_external_contacts)) {
            throw new \InvalidArgumentException('non-nullable include_external_contacts cannot be null');
        }
        $this->container['include_external_contacts'] = $include_external_contacts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


