<?php
/**
 * V1UsageGet200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lockally\SDK\Model;

use \ArrayAccess;
use \Lockally\SDK\ObjectSerializer;

/**
 * V1UsageGet200Response Class Doc Comment
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1UsageGet200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_usage_get_200_response';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'mailboxes_active' => 'int',
        'mailboxes_total' => 'int',
        'domains_verified' => 'int',
        'domains_total' => 'int',
        'messages_sent_last_60s' => 'int',
        'messages_sent_today_utc' => 'int',
        'messages_sent_last_30d' => 'int',
        'bytes_stored' => 'int',
        'rate_cap_per_min' => 'int',
        'daily_msg_quota' => 'int',
        'webhooks_total' => 'int',
        'webhooks_paused' => 'int',
        'generated_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'mailboxes_active' => null,
        'mailboxes_total' => null,
        'domains_verified' => null,
        'domains_total' => null,
        'messages_sent_last_60s' => null,
        'messages_sent_today_utc' => null,
        'messages_sent_last_30d' => null,
        'bytes_stored' => 'int64',
        'rate_cap_per_min' => null,
        'daily_msg_quota' => null,
        'webhooks_total' => null,
        'webhooks_paused' => null,
        'generated_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'mailboxes_active' => false,
        'mailboxes_total' => false,
        'domains_verified' => false,
        'domains_total' => false,
        'messages_sent_last_60s' => false,
        'messages_sent_today_utc' => false,
        'messages_sent_last_30d' => false,
        'bytes_stored' => false,
        'rate_cap_per_min' => false,
        'daily_msg_quota' => false,
        'webhooks_total' => false,
        'webhooks_paused' => false,
        'generated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'mailboxes_active' => 'mailboxes_active',
        'mailboxes_total' => 'mailboxes_total',
        'domains_verified' => 'domains_verified',
        'domains_total' => 'domains_total',
        'messages_sent_last_60s' => 'messages_sent_last_60s',
        'messages_sent_today_utc' => 'messages_sent_today_utc',
        'messages_sent_last_30d' => 'messages_sent_last_30d',
        'bytes_stored' => 'bytes_stored',
        'rate_cap_per_min' => 'rate_cap_per_min',
        'daily_msg_quota' => 'daily_msg_quota',
        'webhooks_total' => 'webhooks_total',
        'webhooks_paused' => 'webhooks_paused',
        'generated_at' => 'generated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'mailboxes_active' => 'setMailboxesActive',
        'mailboxes_total' => 'setMailboxesTotal',
        'domains_verified' => 'setDomainsVerified',
        'domains_total' => 'setDomainsTotal',
        'messages_sent_last_60s' => 'setMessagesSentLast60s',
        'messages_sent_today_utc' => 'setMessagesSentTodayUtc',
        'messages_sent_last_30d' => 'setMessagesSentLast30d',
        'bytes_stored' => 'setBytesStored',
        'rate_cap_per_min' => 'setRateCapPerMin',
        'daily_msg_quota' => 'setDailyMsgQuota',
        'webhooks_total' => 'setWebhooksTotal',
        'webhooks_paused' => 'setWebhooksPaused',
        'generated_at' => 'setGeneratedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'mailboxes_active' => 'getMailboxesActive',
        'mailboxes_total' => 'getMailboxesTotal',
        'domains_verified' => 'getDomainsVerified',
        'domains_total' => 'getDomainsTotal',
        'messages_sent_last_60s' => 'getMessagesSentLast60s',
        'messages_sent_today_utc' => 'getMessagesSentTodayUtc',
        'messages_sent_last_30d' => 'getMessagesSentLast30d',
        'bytes_stored' => 'getBytesStored',
        'rate_cap_per_min' => 'getRateCapPerMin',
        'daily_msg_quota' => 'getDailyMsgQuota',
        'webhooks_total' => 'getWebhooksTotal',
        'webhooks_paused' => 'getWebhooksPaused',
        'generated_at' => 'getGeneratedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('mailboxes_active', $data ?? [], null);
        $this->setIfExists('mailboxes_total', $data ?? [], null);
        $this->setIfExists('domains_verified', $data ?? [], null);
        $this->setIfExists('domains_total', $data ?? [], null);
        $this->setIfExists('messages_sent_last_60s', $data ?? [], null);
        $this->setIfExists('messages_sent_today_utc', $data ?? [], null);
        $this->setIfExists('messages_sent_last_30d', $data ?? [], null);
        $this->setIfExists('bytes_stored', $data ?? [], null);
        $this->setIfExists('rate_cap_per_min', $data ?? [], null);
        $this->setIfExists('daily_msg_quota', $data ?? [], null);
        $this->setIfExists('webhooks_total', $data ?? [], null);
        $this->setIfExists('webhooks_paused', $data ?? [], null);
        $this->setIfExists('generated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['mailboxes_active'] === null) {
            $invalidProperties[] = "'mailboxes_active' can't be null";
        }
        if ($this->container['generated_at'] === null) {
            $invalidProperties[] = "'generated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets mailboxes_active
     *
     * @return int
     */
    public function getMailboxesActive()
    {
        return $this->container['mailboxes_active'];
    }

    /**
     * Sets mailboxes_active
     *
     * @param int $mailboxes_active Mailboxes that are neither disabled nor soft-deleted.
     *
     * @return self
     */
    public function setMailboxesActive($mailboxes_active)
    {
        if (is_null($mailboxes_active)) {
            throw new \InvalidArgumentException('non-nullable mailboxes_active cannot be null');
        }
        $this->container['mailboxes_active'] = $mailboxes_active;

        return $this;
    }

    /**
     * Gets mailboxes_total
     *
     * @return int|null
     */
    public function getMailboxesTotal()
    {
        return $this->container['mailboxes_total'];
    }

    /**
     * Sets mailboxes_total
     *
     * @param int|null $mailboxes_total All mailboxes for this tenant, including disabled/soft-deleted.
     *
     * @return self
     */
    public function setMailboxesTotal($mailboxes_total)
    {
        if (is_null($mailboxes_total)) {
            throw new \InvalidArgumentException('non-nullable mailboxes_total cannot be null');
        }
        $this->container['mailboxes_total'] = $mailboxes_total;

        return $this;
    }

    /**
     * Gets domains_verified
     *
     * @return int|null
     */
    public function getDomainsVerified()
    {
        return $this->container['domains_verified'];
    }

    /**
     * Sets domains_verified
     *
     * @param int|null $domains_verified Domains that have passed DNS verification.
     *
     * @return self
     */
    public function setDomainsVerified($domains_verified)
    {
        if (is_null($domains_verified)) {
            throw new \InvalidArgumentException('non-nullable domains_verified cannot be null');
        }
        $this->container['domains_verified'] = $domains_verified;

        return $this;
    }

    /**
     * Gets domains_total
     *
     * @return int|null
     */
    public function getDomainsTotal()
    {
        return $this->container['domains_total'];
    }

    /**
     * Sets domains_total
     *
     * @param int|null $domains_total domains_total
     *
     * @return self
     */
    public function setDomainsTotal($domains_total)
    {
        if (is_null($domains_total)) {
            throw new \InvalidArgumentException('non-nullable domains_total cannot be null');
        }
        $this->container['domains_total'] = $domains_total;

        return $this;
    }

    /**
     * Gets messages_sent_last_60s
     *
     * @return int|null
     */
    public function getMessagesSentLast60s()
    {
        return $this->container['messages_sent_last_60s'];
    }

    /**
     * Sets messages_sent_last_60s
     *
     * @param int|null $messages_sent_last_60s Sends in the 60-second window ending now. Used by the rate-cap check.
     *
     * @return self
     */
    public function setMessagesSentLast60s($messages_sent_last_60s)
    {
        if (is_null($messages_sent_last_60s)) {
            throw new \InvalidArgumentException('non-nullable messages_sent_last_60s cannot be null');
        }
        $this->container['messages_sent_last_60s'] = $messages_sent_last_60s;

        return $this;
    }

    /**
     * Gets messages_sent_today_utc
     *
     * @return int|null
     */
    public function getMessagesSentTodayUtc()
    {
        return $this->container['messages_sent_today_utc'];
    }

    /**
     * Sets messages_sent_today_utc
     *
     * @param int|null $messages_sent_today_utc Sends since 00:00 UTC. Compared against `daily_msg_quota`.
     *
     * @return self
     */
    public function setMessagesSentTodayUtc($messages_sent_today_utc)
    {
        if (is_null($messages_sent_today_utc)) {
            throw new \InvalidArgumentException('non-nullable messages_sent_today_utc cannot be null');
        }
        $this->container['messages_sent_today_utc'] = $messages_sent_today_utc;

        return $this;
    }

    /**
     * Gets messages_sent_last_30d
     *
     * @return int|null
     */
    public function getMessagesSentLast30d()
    {
        return $this->container['messages_sent_last_30d'];
    }

    /**
     * Sets messages_sent_last_30d
     *
     * @param int|null $messages_sent_last_30d Rolling 30-day send count (not calendar month).
     *
     * @return self
     */
    public function setMessagesSentLast30d($messages_sent_last_30d)
    {
        if (is_null($messages_sent_last_30d)) {
            throw new \InvalidArgumentException('non-nullable messages_sent_last_30d cannot be null');
        }
        $this->container['messages_sent_last_30d'] = $messages_sent_last_30d;

        return $this;
    }

    /**
     * Gets bytes_stored
     *
     * @return int|null
     */
    public function getBytesStored()
    {
        return $this->container['bytes_stored'];
    }

    /**
     * Sets bytes_stored
     *
     * @param int|null $bytes_stored Lifetime sum of `messages.size_bytes` for this tenant.
     *
     * @return self
     */
    public function setBytesStored($bytes_stored)
    {
        if (is_null($bytes_stored)) {
            throw new \InvalidArgumentException('non-nullable bytes_stored cannot be null');
        }
        $this->container['bytes_stored'] = $bytes_stored;

        return $this;
    }

    /**
     * Gets rate_cap_per_min
     *
     * @return int|null
     */
    public function getRateCapPerMin()
    {
        return $this->container['rate_cap_per_min'];
    }

    /**
     * Sets rate_cap_per_min
     *
     * @param int|null $rate_cap_per_min Per-tenant outbound rate cap (sends per minute).
     *
     * @return self
     */
    public function setRateCapPerMin($rate_cap_per_min)
    {
        if (is_null($rate_cap_per_min)) {
            throw new \InvalidArgumentException('non-nullable rate_cap_per_min cannot be null');
        }
        $this->container['rate_cap_per_min'] = $rate_cap_per_min;

        return $this;
    }

    /**
     * Gets daily_msg_quota
     *
     * @return int|null
     */
    public function getDailyMsgQuota()
    {
        return $this->container['daily_msg_quota'];
    }

    /**
     * Sets daily_msg_quota
     *
     * @param int|null $daily_msg_quota Per-tenant daily send quota (UTC day boundary).
     *
     * @return self
     */
    public function setDailyMsgQuota($daily_msg_quota)
    {
        if (is_null($daily_msg_quota)) {
            throw new \InvalidArgumentException('non-nullable daily_msg_quota cannot be null');
        }
        $this->container['daily_msg_quota'] = $daily_msg_quota;

        return $this;
    }

    /**
     * Gets webhooks_total
     *
     * @return int|null
     */
    public function getWebhooksTotal()
    {
        return $this->container['webhooks_total'];
    }

    /**
     * Sets webhooks_total
     *
     * @param int|null $webhooks_total webhooks_total
     *
     * @return self
     */
    public function setWebhooksTotal($webhooks_total)
    {
        if (is_null($webhooks_total)) {
            throw new \InvalidArgumentException('non-nullable webhooks_total cannot be null');
        }
        $this->container['webhooks_total'] = $webhooks_total;

        return $this;
    }

    /**
     * Gets webhooks_paused
     *
     * @return int|null
     */
    public function getWebhooksPaused()
    {
        return $this->container['webhooks_paused'];
    }

    /**
     * Sets webhooks_paused
     *
     * @param int|null $webhooks_paused Webhook subscriptions auto-paused after 50 consecutive failures (LT2).
     *
     * @return self
     */
    public function setWebhooksPaused($webhooks_paused)
    {
        if (is_null($webhooks_paused)) {
            throw new \InvalidArgumentException('non-nullable webhooks_paused cannot be null');
        }
        $this->container['webhooks_paused'] = $webhooks_paused;

        return $this;
    }

    /**
     * Gets generated_at
     *
     * @return \DateTime
     */
    public function getGeneratedAt()
    {
        return $this->container['generated_at'];
    }

    /**
     * Sets generated_at
     *
     * @param \DateTime $generated_at When this snapshot was generated, RFC 3339 UTC.
     *
     * @return self
     */
    public function setGeneratedAt($generated_at)
    {
        if (is_null($generated_at)) {
            throw new \InvalidArgumentException('non-nullable generated_at cannot be null');
        }
        $this->container['generated_at'] = $generated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


