<?php
/**
 * GetStorage200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Lockally\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetStorage200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetStorage200Response
 * @package     Lockally\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetStorage200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetStorage200Response"
     */
    public function testGetStorage200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_bytes"
     */
    public function testPropertyTotalBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alloc_bytes"
     */
    public function testPropertyAllocBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "per_seat_bytes"
     */
    public function testPropertyPerSeatBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "top_mailboxes"
     */
    public function testPropertyTopMailboxes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "top_messages"
     */
    public function testPropertyTopMessages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "generated_at"
     */
    public function testPropertyGeneratedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
