<?php
/**
 * AgentsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Lockally\SDK\Test\Api;

use \Lockally\SDK\Configuration;
use \Lockally\SDK\ApiException;
use \Lockally\SDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AgentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Lockally\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AgentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1ApiKeysKeyIDMailboxesGet
     *
     * List a key's mailbox grants.
     *
     */
    public function testV1ApiKeysKeyIDMailboxesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApiKeysKeyIDMailboxesMailboxIDDelete
     *
     * Revoke a mailbox grant.
     *
     */
    public function testV1ApiKeysKeyIDMailboxesMailboxIDDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ApiKeysKeyIDMailboxesPost
     *
     * Grant a mailbox to a key.
     *
     */
    public function testV1ApiKeysKeyIDMailboxesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AuthWhoamiGet
     *
     * Introspect the calling credentials.
     *
     */
    public function testV1AuthWhoamiGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ContactsLookupGet
     *
     * Who is this sender?.
     *
     */
    public function testV1ContactsLookupGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InboxesGet
     *
     * List granted inboxes.
     *
     */
    public function testV1InboxesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InboxesMailboxMessagesPost
     *
     * Start a new conversation (agent stream).
     *
     */
    public function testV1InboxesMailboxMessagesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InboxesMailboxThreadsGet
     *
     * List conversation threads.
     *
     */
    public function testV1InboxesMailboxThreadsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ThreadsThreadIDGet
     *
     * Get a whole conversation.
     *
     */
    public function testV1ThreadsThreadIDGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ThreadsThreadIDMessagesMessageIDAttachmentsIdxGet
     *
     * Download an attachment.
     *
     */
    public function testV1ThreadsThreadIDMessagesMessageIDAttachmentsIdxGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ThreadsThreadIDMessagesMessageIDGet
     *
     * Get one message with body.
     *
     */
    public function testV1ThreadsThreadIDMessagesMessageIDGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ThreadsThreadIDMessagesMessageIDReadPost
     *
     * Mark read/unread.
     *
     */
    public function testV1ThreadsThreadIDMessagesMessageIDReadPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ThreadsThreadIDReplyPost
     *
     * Reply in-thread (agent stream).
     *
     */
    public function testV1ThreadsThreadIDReplyPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
